### ISSUE TITLE
Build compatibility with Gradle 4.x and Android 10

### ISSUE THREAD

**Issue by spothukuchi** [danialgoodwin/android-app-contactless-vital-signs#2]
I have issues in building this into Android 10 as many of the APIs are deprecated. Moreover build is supporting only Gradle 2.2, bot the latest 4.x. Can you please advice.

**Comment by danialgoodwin** [comment]
I'm sorry I don't have time to update this repo anymore. I'll archive it, and still allows others to fork/fix in their own branches.
